#!/bin/sh

set -x

sudo -v

DISK=$1
FILE=$2

pack() {
  case $FILE in
    *.xz)
      xz | pv -cN out
      ;;
    *.lzop)
      lzop | pv -cN out
      ;;
    *)
      cat
      ;;
  esac
}

dump() {
  sudo pv -cN in ${1:+"$@"}
}

dump $DISK|pack > $FILE.lzop
echo
echo "You may now safely remove the card."
echo
myxz $FILE.lzop
rm $FILE.lzop
